env:
  browser: true
  es6: true
  jest: true
extends:
  - airbnb
  - airbnb/hooks
  - 'plugin:testing-library/react'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
plugins:
  - react
  - import
  - testing-library
settings:
  import/resolver: webpack
rules:
  import/no-extraneous-dependencies:
    - "error"
    - "devDependencies": true
