env:
  browser: true
  es6: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:testing-library/react'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - import
  - testing-library
settings:
  import/resolver: webpack
rules:
  import/no-extraneous-dependencies:
    - "error"
    - "devDependencies": true
